### ISSUE TITLE
Error Undefined function or variable 'filterDataSet'.

### ISSUE THREAD

**Issue by hchh03** [jimmyDunne/c3d2OpenSim#10]
Hello
I want to run this function: c3d2Opensim
But there is error below:
Undefined function or variable 'filterDataSet'.

Error in c3d2Opensim (line 111)
    structData.marker_data.Markers = filterDataSet(structData.marker_data.Markers,...

Please help me to solve this problem.
Thanks

**Comment by jimmyDunne** [comment]
You need to add all folders in the downloaded package to your Matlab path. The error is associated with Matlab not being able to find the function.
