### ISSUE TITLE
printtrc

### ISSUE THREAD

**Issue by cmkillelea** [jimmyDunne/c3d2OpenSim#11]
Wehen I try to run c3d files through the c3d2opensim command I get the following error.  I am using the sample data give in the testdata folder provided

   No filtering done on mrks
   Printing marker trajectory file
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in printTRC (line 45)
    fprintf(fid,'PathFileType\t4\t(X/Y/Z)\t%s\n',name);

Error in c3d2Opensim (line 121)
    printTRC(structData.marker_data.Markers,...         % Markers

**Comment by jimmyDunne** [comment]
You probably don't have permission to print the files to the folder. Make sure you have admin priv on your machine
