### ISSUE TITLE
Error undefined function or variable

### ISSUE THREAD

**Issue by ajinkya28121992** [jimmyDunne/c3d2OpenSim#4]
Hello sir. I followed all the steps given in the description for c3d2Opensim but after giving command, error pops up saying ' Undefined function or variable c3d2Opensim. Can you please provide the solution.

**Comment by CyrilDonnelly** [comment]
It sounds like you did not set your function paths correctly

**Comment by ajinkya28121992** [comment]
can you tell me how to do it?

**Comment by CyrilDonnelly** [comment]
I left a demo video and instructions with the reps at the vicon booth.

**Comment by ajinkya28121992** [comment]
Can you give me the link?

**Comment by jimmyDunne** [comment]
Below are some links that may help...

http://www.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html
http://www.mathworks.com/help/matlab/ref/pathtool.html
