### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by Rtms1984** [jimmyDunne/c3d2OpenSim#5]
??? Undefined function or method 'filterDataSet' for input arguments of type 'struct'.

Error in ==> c3d2Opensim at 111
    structData.marker_data.Markers = filterDataSet(structData.marker_data.Markers,...

It happened when C3D file was loaded
you know what does it mean?

**Comment by jimmyDunne** [comment]
there is an issue with the data structure being passed to the filter. Do you have markers in the trial?

**Comment by Rtms1984** [comment]
yes. so what is the problem?

**Comment by jimmyDunne** [comment]
This is either to do with the data in the c3d file or how you are passing the arguments for the filter.

**Comment by Rtms1984** [comment]
I used c3d files of our lab, so there is not gonna be any problem
