### ISSUE TITLE
Compute center of pressure (CoP)

### ISSUE THREAD

**Issue by sceu** [jimmyDunne/c3d2OpenSim#6]
Thank you for your contribution and providing this useful script. 
I simulated a gait trial with OpenSim using the c3d2OpenSim script to process the c3d-file into a trc- and mot-file. In my c3d-file a force plate type 2 was used. Unfortunately, I had some issues with the calculated CoP.

In order to calculate the center of pressure (CoP) and the moments Tx, Ty and Tz in the function "computeCOP.m", the values stored in "structData.fp_data.GRF_data" are used. I think that this procedure is not correct. The values in "GRF_data" (P, F and M) correspond to the ground reaction wrenches of the force plate. In my opinion, the ground reaction wrenches already contain the coordinates of the CoP (stored in P) and the moments Tx, Ty and Tz (stored in M). If one would like to calculate the CoP and the corresponding moments Tx, Ty, Tz, the values Fx, Fy, Fz, Mx, My, Mz would have to be used (stored e.g. in structData.analog_data.Channels).

I adjusted the "computeCOP.m" function according to my findings (COPx = ...GRF_data(i).P(:,1), etc.) and afterwards the CoP made more sense for my simulated gait trial. I also adjusted the moments (Tx = GRF_data(i).M(:,1), etc.). 

Kind regards,
Erika

**Comment by jimmyDunne** [comment]
Thanks, Erika!

much appreciated.
