### ISSUE TITLE
btk-c3d Matlab binaries link correction

### ISSUE THREAD

**Issue by ainhoaetxeberria** [jimmyDunne/c3d2OpenSim#7]
Hello,
I tried to open the 'btk-c3d Matlab binaries' link posted in the Quick Start section but it leads me to an error. I have searched it directly in Google Code and it is possible to download the 'btk' file there. The correct link is: https://code.google.com/archive/p/b-tk/downloads?page=1

**Comment by jimmyDunne** [comment]
thanks!!
