### ISSUE TITLE
btk files

### ISSUE THREAD

**Issue by blj192** [jimmyDunne/c3d2OpenSim#9]
Initially, while the BTK files were added to the MATLAB path, I received an error that btkReadAcquisition was undefined. This was because it is located in an @method folder. I tried renaming without the @, but received the error 'MEX file for btkReadAcquisition not found'. Any help would be appreciated.

**Comment by blj192** [comment]
Actually, I was able to fix this issue. Followup issue is that no forces were transferred to my .mot file, and all of them are set to 0.

**Comment by jimmyDunne** [comment]
This sounds like a BTK issue. Not sure I can help on this one.
